steps:
  - id: 'Terraform Install'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['./terraform/TfInstall.sh']

  - id: 'Terraform run'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['./tf/TfBuild.sh']
  