steps:
  - id: 'Terraform Install'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['./tf/TfInstall.sh']

  - id: 'Terraform run'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['./tf/TfBuild.sh']
  
  - id: 'Terraform main.tf'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['./tf/maintf.sh']
  