steps:
  - id: 'Project creation'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['./tf/ProjectDeploy.sh']
  
  - id: 'Terraform Install and Run'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['./tf/TfInstall_Run.sh']
